# -*- coding: utf-8 -*-
"""LVADSUSR98_Marimuthu p_Lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uGSJgsAaigDTm_-DOBegH2gaOd_DVdsk
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv("/content/booking.csv")
print(data.info())
data = data.dropna()
data = data.drop_duplicates()

X = pd.get_dummies(data.drop(columns=['Booking_ID', 'booking status']))
y = data['booking status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
clf = LogisticRegression()
clf.fit(X_train, y_train)
predicted_cancelled = clf.predict(X_test)

y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label='Canceled')
recall = recall_score(y_test, y_pred, pos_label='Canceled')
f1 = f1_score(y_test, y_pred, pos_label='Canceled')
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:")
print(conf_matrix)