# -*- coding: utf-8 -*-
"""LVADSUSR98_Marimuthu P_Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-XxPQpiRGNwfYM2LTRyoVadUrcykGGv
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
data = pd.read_csv("/content/expenses.csv")
print(data.info())
data = data.dropna()
data = data.drop_duplicates()
#categorical to numerical
columns_to_encode = ['smoker','region','sex']
data = pd.get_dummies(data, columns=columns_to_encode)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

lr_model = LinearRegressionGD(learning_rate=0.01, n_iterations=1000)
lr_model.fit(X_train, y_train)

predictions = lr_model.predict(X_test)


accuracy = model.score(X_test, y_test)

MSE = mean_squared_error(y_test, y_pred)

R_squared = r2_score(y_test, y_pred)

RMSE = sqrt(MSE)


#print("predictions:", predictions)
print("Accuracy:", accuracy)
print("MSE:", MSE)
print("R-squared:", R_squared)
print("RMSE:", RMSE)