# -*- coding: utf-8 -*-
"""LVADSUSR98_Marimuthu P_Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-XxPQpiRGNwfYM2LTRyoVadUrcykGGv
"""

import pandas as pd
from sklearn.model_selection import train_test_split
data = pd.read_csv("/content/expenses.csv")
print(data.info())
data = data.dropna()
data = data.drop_duplicates()
#categorical to numerical
columns_to_encode = ['smoker','region','sex']
data = pd.get_dummies(data, columns=columns_to_encode)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

lr_model = LinearRegressionGD(learning_rate=0.01, n_iterations=1000)
lr_model.fit(X_train, y_train)

predictions = lr_model.predict(X_test)


mse = mean_squared_error(y_test, predictions)
r_squared = r2_score(y_test, predictions)
rmse = np.sqrt(mse)

print("Mean Squared Error (MSE):", mse)
print("R-squared:", r_squared)
print("Root Mean Squared Error (RMSE):", rmse)